services:
  storybook:
    build: ./client
    container_name: example-app-sb
    restart: always
    ports:
      - "4002:4002"
    command: npm run storybook
    volumes:
      - ./client:/app
      - /app/node_modules
  app:
    build: ./client
    container_name: example-app-fe
    restart: always
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - API_URL=http://api:4000
      - VITE_PORT=4001
    depends_on:
      - api
    volumes:
      - ./client:/app
      - /app/node_modules
  api:
    build: ./server
    container_name: example-app-api
    restart: always
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/example_tracker
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=super_secret_key
    depends_on:
      - postgres
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules

  postgres:
    image: postgres:15
    container_name: example-postgres
    restart: always
    environment:
      POSTGRES_DB: example_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: example-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres-data: