version: '3.9'

services:
  app:
    build: .
    container_name: example-app
    restart: always
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/example_tracker
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=super_secret_key
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:15
    container_name: example-postgres
    restart: always
    environment:
      POSTGRES_DB: example_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: example-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres-data: